### ISSUE TITLE
Error on install - ModuleNotFoundError:

### ISSUE THREAD

**Issue by Hu3diger** [heronotears/lazyxml#16]
I'm trying to install the Lazyxml library, but I don't have success.
I'm running the following command:
`pip install lazyxml`

And appear this error
![Screenshot_19](https://user-images.githubusercontent.com/30418918/57935381-07a31080-7898-11e9-9772-e88747bad039.png)

**Comment by heronotears** [comment]
Which python version are you using?

**Comment by tanpengsccd** [comment]
python 3.7

**Comment by waynedyck** [comment]
@tanpengsccd, I just submitted pull request #18 which updates the repo to support Python 3.7.x and greater. If you want, try that and see if it works.

**Comment by tanpengsccd** [comment]
@heronotears hope to merge pr for python3.7

**Comment by mfriedenhagen** [comment]
Same error here on macOS Big Sur (11.0.1) using Python 3.8.2:
```
$ python3 -mpip install lazyxml
Looking in indexes: https://repo.example.com/artifactory/api/pypi/pypi-mam/simple
Collecting lazyxml
  Downloading https://repo.example.com/artifactory/api/pypi/pypi-mam/packages/packages/eb/ca/9fe2223845fb0e6637a99fe485fc3535e471b12e4a016332c9cabf0264a6/lazyxml-1.2.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /private/tmp/foo/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hf/m19pkv557r98ympr015qxz840000gp/T/pip-install-owfudze8/lazyxml/setup.py'"'"'; __file__='"'"'/private/var/folders/hf/m19pkv557r98ympr015qxz840000gp/T/pip-install-owfudze8/lazyxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/hf/m19pkv557r98ympr015qxz840000gp/T/pip-install-owfudze8/lazyxml/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hf/m19pkv557r98ympr015qxz840000gp/T/pip-install-owfudze8/lazyxml/setup.py", line 16, in <module>
        import lazyxml
      File "/private/var/folders/hf/m19pkv557r98ympr015qxz840000gp/T/pip-install-owfudze8/lazyxml/lazyxml/__init__.py", line 15, in <module>
        from . import builder
      File "/private/var/folders/hf/m19pkv557r98ympr015qxz840000gp/T/pip-install-owfudze8/lazyxml/lazyxml/builder.py", line 7, in <module>
        import utils
    ModuleNotFoundError: No module named 'utils'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by waynedyck** [comment]
@mfriedenhagen you could try merging pull request #18 with the source and see if that works. My pull request updated the source to work with Python 3.7.x as a minimum.
